Update Cloudbuild to fail when subcommands fail. (#52)
* Adds a check that required env vars are set

* adds the intial set -e command

* checks exact matching Secret name exists. Existing --filter checks name includes, so multiple matches are possible.

* Checks that an exact match exists for the redis instance

* replaces forward slashes in branch names when creating service names, because forward slashes are illegal there.

* since backticks are not parsed as commands in env entries, checking if command substitution using  works.

* revert branch name modifications

* updates all list commands to check for exact match

* Updates missed list commands to check for exact match

* tweak for topics which use ids vs resource names

* Tests using SHORT_SHA instead of branch name to guarantee unique Cloud Run service names

* Adds a teardown step

* Adds cleanup for cloud run services.

* adds region to cloud run delete steps

* adds --quiet to auto-confirm

* Adds build steps

* fix a typo in step 1

* remove env vars from args

* removes cloud run service cleanup steps

diff --git a/aa-integration-backend/cloudbuild.yaml b/aa-integration-backend/cloudbuild.yaml
--- a/aa-integration-backend/cloudbuild.yaml
+++ b/aa-integration-backend/cloudbuild.yaml
@@ -15,19 +15,25 @@
 # An example of Cloud Build configuration file to run deployment script for CI/CD pipeline.
 
 steps:
-- id: 'branch name'
+- id: 'Check required variables'
   name: 'alpine'
   entrypoint: 'sh'
   args:
   - '-c'
   - |
       echo "***********************"
-      echo "$BRANCH_NAME"
-      echo "$PROJECT_ID"
-      echo "$SERVICE_ACCOUNT_EMAIL"
+      echo "BRANCH_NAME: ${BRANCH_NAME}"
+      echo "SHORT_SHA: ${SHORT_SHA}"
+      echo "PROJECT_ID: ${PROJECT_ID}"
+      echo "SERVICE_ACCOUNT_EMAIL: ${SERVICE_ACCOUNT_EMAIL}"
       echo "***********************"
+      if [[ ! -v $BRANCH_NAME || ! -v $SHORT_SHA || ! -v $PROJECT_ID || ! -v $SERVICE_ACCOUNT_EMAIL ]]; then
+        echo "A required variable is not set, failing the build."
+        exit 1
+      fi
 
 - name: 'gcr.io/cloud-builders/gcloud'
+  id: 'Deploy Agent Assist integration backend'
   entrypoint: 'bash'
   args: ['aa-integration-backend/deploy.sh']
   env:
@@ -35,5 +41,5 @@ steps:
   - 'ADMIN_ACCOUNT=$SERVICE_ACCOUNT_EMAIL'
   - 'AUTH_OPTION=Skip'
   - 'BACKEND_DIR=/aa-integration-backend'
-  - 'CONNECTOR_SERVICE_NAME=ui-connector-presubmit-${BRANCH_NAME}'
-  - 'INTERCEPTOR_SERVICE_NAME=cloud-pubsub-interceptor-presubmit-${BRANCH_NAME}'
+  - 'CONNECTOR_SERVICE_NAME=ui-connector-presubmit-${SHORT_SHA}'
+  - 'INTERCEPTOR_SERVICE_NAME=cloud-pubsub-interceptor-presubmit-${SHORT_SHA}'
